# Generated by Django 5.2.7 on 2025-10-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='minimum_split_time',
            field=models.IntegerField(blank=True, default=15, help_text='The minimum amount of time to spend on this task in a given timeblock'),
        ),
    ]
