# Generated by Django 5.2.7 on 2025-10-17 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_minimum_split_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='delete_if_deadline_passed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_duration',
            field=models.IntegerField(default=1, help_text='An estimate in minutes of the time required to complete this task', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.TextField(default='task_name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='prerequisites',
            field=models.ManyToManyField(related_name='subsequent_tasks', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=5, help_text='The priority of this task on a scale from 1 to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='task',
            name='splittable',
            field=models.BooleanField(blank=True, default=True, help_text='Whether or not this task can be split into separate timeblocks.'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('ac', 'active'), ('c', 'completed'), ('ab', 'abandoned')], default='ac', max_length=2),
        ),
    ]
