# Generated by Django 5.2.7 on 2025-10-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_date_completed_task_date_created_task_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, null=True, related_name='subsequent_tasks', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='splittable',
            field=models.BooleanField(blank=True, default=False, help_text='Whether or not this task can be split into separate timeblocks.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('ac', 'active'), ('c', 'completed')], default='ac', max_length=2),
        ),
    ]
