# Generated by Django 5.2.7 on 2025-10-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_name_alter_task_prerequisites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='subsequent_tasks', to='tasks.task'),
        ),
    ]
